app:
  name: FastFood
  mercadopagotoken: ${MERCADO_PAGO_TOKEN}
  url: ${APPLICATION_URL:http://127.0.0.1:8080}
spring:
  application:
    name: fastfood
  datasource:
    url: jdbc:postgresql://localhost:5432/fastfood
    username: fastfood_user
    password: fastfood_password
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none # Flyway gerencia
    show-sql: true
  docker:
    compose:
      file: ./run/postgres-dev.yml
  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger