apiVersion: v1
kind: Service
metadata:
  name: fastfood-produto
  namespace: fastfood
spec:
  type: LoadBalancer
  selector:
    app: fastfood-produto
  ports:
    - port: 8080
      targetPort: 8080
