apiVersion: v1
kind: Service
metadata:
  name: fastfood-produto
  namespace: fastfood
spec:
  type: NodePort
  selector:
    app: fastfood-produto
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31001
