apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}-deployment
  namespace: fastfood
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      containers:
        - name: ${APP_NAME}
          image: ${DOCKER_USERNAME}/${APP_NAME}:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_PASSWORD
            - name: SPRING_DATASOURCE_DB
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_DB
            - name: AWS_COGNITO_APP_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: cognito-config
                  key: AWS_COGNITO_APP_CLIENT_ID
            - name: AWS_COGNITO_ISSUER_URI
              valueFrom:
                secretKeyRef:
                  name: cognito-config
                  key: AWS_COGNITO_ISSUER_URI
            - name: AWS_COGNITO_JWK_URI
              valueFrom:
                secretKeyRef:
                  name: cognito-config
                  key: AWS_COGNITO_JWK_URI
            - name: AWS_COGNITO_REGION
              valueFrom:
                secretKeyRef:
                  name: cognito-config
                  key: AWS_COGNITO_REGION
            - name: AWS_COGNITO_USER_POOL_ID
              valueFrom:
                secretKeyRef:
                  name: cognito-config
                  key: AWS_COGNITO_USER_POOL_ID

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
