apiVersion: v1
kind: Service
metadata:
  name: fastfood-produto
  namespace: fastfood
spec:
  type: LoadBalancer
  selector:
    app: fastfood-pedido
  ports:
    - name: http
      port: 80
      targetPort: 8080