version: '3.9'
services:
  postgres:
    image: postgres:17
    container_name: postgres_fastfood
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastfood_network

  fastfood_app:
    build: ./../
    image: fastfood_app_produtos:latest
    container_name: fastfood_app_produtos
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      MERCADO_PAGO_TOKEN: ${MERCADO_PAGO_TOKEN}
    ports:
      - "9901:8080"
    depends_on:
      - postgres
    networks:
      - fastfood_network
volumes:
  postgres_data:

networks:
  fastfood_network: