name: CD - Build e Push Docker

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Fastfood Pedidos'
        required: true
        default: fastfood-pedido
      deploy:
        description: 'Fazer deploy após build?'
        required: false
        default: 'false'

  push:
    branches:
      - '**'   # todas as branches

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.vars.outputs.version }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build com Maven
        run: mvn clean package -DskipTests

      - name: Extrair versão da tag
        id: vars
        run: echo "version=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -f run/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/${{ github.event.inputs.app_name }}:${{ steps.vars.outputs.version }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/${{ github.event.inputs.app_name }}:${{ steps.vars.outputs.version }} ${{ secrets.DOCKER_USERNAME }}/${{ github.event.inputs.app_name }}:latest

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ github.event.inputs.app_name }}:${{ steps.vars.outputs.version }}
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ github.event.inputs.app_name }}:latest

  deploy:
    if: ${{ github.event.inputs.deploy == 'true' }}
    needs: build-and-push
    uses: ./.github/workflows/deploy.yml
    with:
      app_name: ${{ github.event.inputs.app_name }}
